### ISSUE TITLE
`node build` fails on OS X

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#607]
# Issue

Running `node build` (to run a local node server from a `frontend` build) currently fails on OS X. Technically, the process starts and runs, but all requests return a `500` error.

## Steps to reproduce

1. Check out `v199`
   ```bash
   git checkout v199
   ```
2. Build the application
   ```bash
   npm run build
   ```
3. Start the node service
   ```bash
   export TS_PUBLIC_BACKEND_URL=https://tradingstrategy.ai:443/api
   node build
   ```
4. open http://127.0.0.1:3000/ in a browser
5. Note `500` error in browser
   - **expected:** page loads
6. Note error output in `node` process:
   ```
   TypeError: fetch failed
       at fetch (file:///Users/ken/Code/tradingstrategy/frontend/build/shims.js:20346:13)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async Object.fetch (file:///Users/ken/Code/tradingstrategy/frontend/build/server/index.js:2726:12)
       at async file:///Users/ken/Code/tradingstrategy/frontend/build/server/index.js:1149:20
       at async load (file:///Users/ken/Code/tradingstrategy/frontend/build/server/chunks/0-9b8829c7.js:2:16)
       at async load_data (file:///Users/ken/Code/tradingstrategy/frontend/build/server/index.js:1131:18)
       at async file:///Users/ken/Code/tradingstrategy/frontend/build/server/index.js:2460:18 {
     cause: [Error: 001ED2E601000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
     ] {
       library: 'SSL routines',
       reason: 'wrong version number',
       code: 'ERR_SSL_WRONG_VERSION_NUMBER'
     }
   }
   ```

## Investigation

This issue was introduced in `v199`. It appears to be related to the pre-rendering of `chains` data. It must not be occurring on production or `frontend` would not be working.

It may not be worth spending much time to investigate this – it may just be faster to pull out the pre-rendering code and replace it with NodeCashe which is being used is a few other places. The net result is roughly the same – the web site should work even if `api/chains` is failing, but we want changes to `api/chains` to automatically propagate to `frontend`.

**Comment by kenkunz** [comment]
It turns out the use of pre-rendering was a red herring. The actual cause was the request from `+layout.ts` to `/data/chains`.

When running `node build`, SvelteKit by default assumes a protocol of `https`. So the request to a local endpoint (only available on `http` in `dev`) fails.

The solution is to set an origin ENV variable:
```bash
export FRONTEND_ORIGIN=http://127.0.0.1:3000
node build
```
